<a href="https://www.kaggle.com/code/akshitaa2606/yelp-project-team9?scriptVersionId=205239074" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import json
import pandas as pd
data_file = open("/kaggle/input/yelp-dataset/yelp_academic_dataset_review.json")
data = []
for line in data_file:
    data.append(json.loads(line))
review_df = pd.DataFrame(data)
data_file.close()

In [ ]:
review_df.head()

In [ ]:
review_df.info()

In [ ]:
user_df = review_df[['user_id']].drop_duplicates().reset_index(drop=True)
business_df = review_df[['business_id']].drop_duplicates().reset_index(drop=True) #drop duplicates

**Table: Reviews**

Columns:
* review_id (VARCHAR): Unique identifier for each review.
* user_id (VARCHAR): Unique identifier for the user who left the review; links to Users table.
* business_id (VARCHAR): Unique identifier for the business being reviewed; links to Business table.
* stars (FLOAT): Star rating provided in the review, on a scale of 1.0 to 5.0.
* useful (INT): Count of "useful" votes this review received.
* funny (INT): Count of "funny" votes this review received.
* cool (INT): Count of "cool" votes this review received.
* text (TEXT): Full text of the review, providing content feedback.
* date (DATE): Date the review was written.

**Primary Key:** review_id

**Foreign Keys:**
* user_id references Users table (One-to-Many).
* business_id references Business table (One-to-Many).

Data Source: Extracted from yelp_academic_dataset_review.json JSON file.

In [ ]:
import json
import pandas as pd
data_file = open("/kaggle/input/yelp-dataset/yelp_academic_dataset_business.json")
data = []
for line in data_file:
    data.append(json.loads(line))
business_df = pd.DataFrame(data)
data_file.close()

In [ ]:
business_df.head()

In [ ]:
business_df.info()

**Table: Business**

Columns:

* business_id (VARCHAR): Unique identifier for each business.
* name (VARCHAR): Name of the business.
* address (VARCHAR): Street address of the business.
* city (VARCHAR): City where the business is located.
* state (VARCHAR): State where the business is located.
* postal_code (VARCHAR): Postal code for the business location.
* latitude (FLOAT): Latitude coordinate of the business location.
* longitude (FLOAT): Longitude coordinate of the business location.
* stars (FLOAT): Average rating of the business (scale of 1.0 to 5.0).
* review_count (INT): Total number of reviews for the business.
* is_open (INT): Indicator if the business is open (1 for open, 0 for closed).
* attributes (JSON/TEXT): Additional business attributes (e.g., parking availability, payment options) stored as JSON text.
* categories (TEXT): Categories or types of business (e.g., "Restaurant, Fast Food").
* hours (JSON/TEXT): Opening hours of the business stored as JSON text.

**Primary Key:** business_id

**Data Source:** Extracted from yelp_academic_dataset_business.json JSON file.

In [ ]:
import json
import pandas as pd
data_file = open("/kaggle/input/yelp-dataset/yelp_academic_dataset_checkin.json")
data = []
for line in data_file:
    data.append(json.loads(line))
checkin_df = pd.DataFrame(data)
data_file.close()

In [ ]:
checkin_df.head()

In [ ]:
checkin_df.info()

In [ ]:
checkin_df['date'] = pd.to_datetime(checkin_df['date'], format='%Y-%m-%d %H:%M:%S', errors='coerce') # convert to datetime format

In [ ]:
checkin_df = checkin_df.dropna(subset=['date']) # drop dates which are null

**Table: Checkins**

Columns:

* business_id (VARCHAR): Unique identifier for each business; links to the Business table.
* date (DATETIME): Date and time of each check-in for the business, formatted as a timestamp or date.

**Primary Key:** (Composite primary key on business_id and date if each check-in event is unique by business and date).

**Foreign Keys:**

business_id references Business table (One-to-Many).

Data Source: Extracted from yelp_academic_dataset_checkin.json JSON file.

In [ ]:
import json
import pandas as pd
data_file = open("/kaggle/input/yelp-dataset/yelp_academic_dataset_tip.json")
data = []
for line in data_file:
    data.append(json.loads(line))
tip_df = pd.DataFrame(data)
data_file.close()

In [ ]:
tip_df.head()

In [ ]:
tip_df.info()

**Table: Tips**

Columns:

* user_id (VARCHAR): Unique identifier for each user; links to the Users table.
* business_id (VARCHAR): Unique identifier for each business; links to the Business table.
* text (TEXT): Content of the tip provided by the user, describing their experience or suggestions.
* date (DATETIME): Date and time when the tip was posted.
* compliment_count (INT): Number of compliments received by the tip from other users.

**Primary Key:** (Composite primary key on user_id, business_id, and date if each tip is unique by user, business, and date).

**Foreign Keys:**

user_id references Users table (One-to-Many).
business_id references Business table (One-to-Many).

**Data Source:**

Extracted from yelp_academic_dataset_tip.json JSON file.

In [ ]:
import json
import pandas as pd
data_file = open("/kaggle/input/yelp-dataset/yelp_academic_dataset_user.json")
data = []
for line in data_file:
    data.append(json.loads(line))
user_df = pd.DataFrame(data)
data_file.close()

In [ ]:
user_df.head()

In [ ]:
user_df.info()

**Table: Users**

Columns:

* user_id (VARCHAR): Unique identifier for each user.
* name (VARCHAR): Name of the user.
* review_count (INT): Total number of reviews submitted by the user.
* yelping_since (DATETIME): Date the user joined Yelp.
* useful (INT): Count of useful votes received by the user’s reviews.
* funny (INT): Count of funny votes received by the user’s reviews.
* cool (INT): Count of cool votes received by the user’s reviews.
* elite (TEXT): Years in which the user held elite status, formatted as a comma-separated string.
* friends (TEXT): List of user IDs representing the user’s friends, formatted as a comma-separated string.
* fans (INT): Number of fans the user has on Yelp.
* average_stars (FLOAT): Average star rating given by the user across all reviews.
* compliment_hot (INT): Count of "hot" compliments received by the user.
* compliment_more (INT): Count of "more" compliments received by the user.
* compliment_profile (INT): Count of "profile" compliments received by the user.
* compliment_cute (INT): Count of "cute" compliments received by the user.
* compliment_list (INT): Count of "list" compliments received by the user.
* compliment_note (INT): Count of "note" compliments received by the user.
* compliment_plain (INT): Count of "plain" compliments received by the user.
* compliment_cool (INT): Count of "cool" compliments received by the user.
* compliment_funny (INT): Count of "funny" compliments received by the user.
* compliment_writer (INT): Count of "writer" compliments received by the user.
* compliment_photos (INT): Count of "photos" compliments received by the user.

**Primary Key:** user_id

**Data Source:** Extracted from yelp_academic_dataset_user.json JSON file.

In [ ]:
tip_df['date'].min()

The oldest tip is of 2009.

**Kaggle to Azure Connection-**

In [ ]:
from sqlalchemy import create_engine
!pip install PyMySql
import pymysql
import sqlalchemy

In [ ]:
!pip install pyodbc

!apt-get update
!apt-get install -y unixodbc-dev

 #install Microsoft ODBC Driver for SQL Server
!curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
!curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | tee /etc/apt/sources.list.d/msprod.list
!apt-get update
!ACCEPT_EULA=Y apt-get install -y msodbcsql17

In [ ]:
import pyodbc

connection_string = (
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=akshita.database.windows.net;'
    'DATABASE=akshita;'
    'UID=akshita;'
    'PWD=aksh@123;'
)

try:
    conn = pyodbc.connect(connection_string, timeout=30)
    print("Connection successful!")
    conn.close()
except pyodbc.Error as e:
    print("Connection failed:", e)

In [ ]:
import pyodbc
from sqlalchemy import create_engine

# Define a connection function for SQLAlchemy to use
def get_pyodbc_connection():
    return pyodbc.connect(
        'DRIVER={ODBC Driver 17 for SQL Server};'
        'SERVER=akshita.database.windows.net;'
        'DATABASE=akshita;'
        'UID=akshita;'
        'PWD=aksh@123;'
        'timeout=60;'
    )

# Create the SQLAlchemy engine using the connection function
engine = create_engine("mssql+pyodbc://", creator=get_pyodbc_connection)

try:
    with engine.connect() as connection:
        print("SQLAlchemy Connection successful!")
except Exception as e:
    print("SQLAlchemy Connection failed:", e)

**PORT TO AZURE**

In [ ]:
checkin_df.to_sql(name = 'checkin', con=engine, if_exists='replace', index=False)

*Converting to datetime format :*

In [ ]:
review_df['date'] = pd.to_datetime(review_df['date'])  # Ensure 'date' column is in datetime format

In [ ]:
review_df.to_sql(name = 'Reviews', con=engine, if_exists='replace', index=False)

In [ ]:
import sqlalchemy
business_df.to_sql(name = "Business", con = engine, if_exists='replace', index=True, dtype={'attributes': sqlalchemy.types.JSON, 'hours': sqlalchemy.types.JSON}, chunksize=50000)

In [ ]:
tip_df.to_sql(name = 'Tips', con=engine, if_exists='replace', index=False)

In [ ]:
user_df.to_sql(name = 'Users', con=engine, if_exists='replace', index=True, chunksize=50000)

# QUERIES

1. FIRST QUERY: Analyse the categories which do not have many restaurants

In [ ]:
query = """
SELECT categories,count(*) as countOfCategories
FROM business
WHERE categories LIKE '%Restaurant%' and is_open=1
group by categories order by countOfCategories asc ;
"""

# Execute the query and store the results in a DataFrame
df_popular_categories = pd.read_sql(query, engine)
print(df_popular_categories)

Here , we can see categories of Acai Bowls are very less. Let's explore this category.

2. SECOND QUERY: Analyse the count of Acai Bowls category in each city

In [ ]:
query = """
SELECT city, COUNT(*) AS cnt
FROM business
WHERE categories LIKE 'Acai Bowls%'
GROUP BY city
ORDER BY cnt ASC
"""

# Execute the query and store the results in a DataFrame
df_popular_loc = pd.read_sql(query, engine)
print(df_popular_loc)

Acai restaurants are highest in Tampa. Let's pick St.Louis

3. THIRD QUERY: Check details of 1 business which serves Acai Bowls

In [ ]:
query = """
select business_id, name from business
where  city like 'St Louis' and categories like 'Acai Bowls%' and is_open=1

"""

df_bus = pd.read_sql(query, engine)
print(df_bus)

only 1 Acai Bowl restaurant in St.Louis

4. FOURTH QUERY: Analyse the reviews of the business

In [ ]:
query = """
select text from reviews
where business_id='XriKtVR4J_DG-R0xFqYXEg'

"""

df_rev = pd.read_sql(query, engine)
print(df_rev)

Many reviews state that acai bowls are bland and not good so there is a market for acai bowls.

5. FIFTH QUERY: check ratings of the business

In [ ]:
query = """
select avg(stars) from reviews
where business_id='XriKtVR4J_DG-R0xFqYXEg';
"""

# Execute the query and store the results in a DataFrame
df_stars = pd.read_sql(query, engine)
print(df_stars)

Average rating of this is 4.0

6. SIXTH QUERY: check tips of the business

In [ ]:

query = """
select * from tips
where business_id='XriKtVR4J_DG-R0xFqYXEg';
"""

# Execute the query and store the results in a DataFrame
df_tips = pd.read_sql(query, engine)
print(df_tips)

7. SEVENTH QUERY: check opening hours of the business

In [ ]:
query = """
select hours from business
where business_id='XriKtVR4J_DG-R0xFqYXEg'

"""

# Execute the query and store the results in a DataFrame
df_hours = pd.read_sql(query, engine)
print(df_popular_categories_atpostal)

Could be a market for early hours before 7 am and opens till late as well.

8. EIGHTH QUERY- check if there is a market for breakfast at St Louis

In [ ]:
query = """
select text from reviews
where (text like '%breakfast%'
or text like '%morning%')

and business_id in (select business_id from business where  city like 'St Louis')

"""

# Execute the query and store the results in a DataFrame
df_mrng = pd.read_sql(query, engine)
print(df_mrng)

There are many people who go out for breakfast so great opportunity here.

9. NINTH QUERY: check busiest postal codes in St Louis

In [ ]:
query = """
select top 5 postal_code, count(business_id) as bus_cnt  from business where  city like 'St Louis'
group by postal_code order by bus_cnt desc;

"""

# Execute the query and store the results in a DataFrame
df_busy_codes = pd.read_sql(query, engine)
print(df_busy_codes)

We could consider opening our Acai Bowl restaurant at 63108 or 63110

10. TENTH QUERY: check postal code of 1 Acai Bowl business which we explored before

In [ ]:
query = """
select postal_code from business
where business_id='XriKtVR4J_DG-R0xFqYXEg'

"""

# Execute the query and store the results in a DataFrame
df_postal = pd.read_sql(query, engine)
print(df_postal)

Since the business is already open at 63108 we should open at 63110 to attract new customers.

 After running all the above queries and exploring the market from the yelp database , we have come to the conclusion of opening a restaurant that serves Acai Bowls in St Louis at the postal code 63110.